name = "MinimaxCalibratedEBayes"
uuid = "c903c015-ce1d-4e5c-9374-957b0f33d7cc"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com>"]
version = "0.1.0"

[deps]
EBayes = "bad9efff-1a8e-41fb-9e7d-5d6f530fb0a3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
